### ISSUE TITLE
CT cannot read property pointer

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/tambo#122] opened 2020-09-11 14:45 UTC
```
tambo : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599810432778/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1599810432778%22%2C%22timestamp%22%3A1599813984504%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'pointer' of undefined
TypeError: Cannot read property 'pointer' of undefined
at oA.canPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599810432778/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1599810432778%22%2C%22timestamp%22%3A1599813984504%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:635610)
at oA.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599810432778/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1599810432778%22%2C%22timestamp%22%3A1599813984504%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:635808)
at oA.click (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599810432778/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1599810432778%22%2C%22timestamp%22%3A1599813984504%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:638315)
at vb.a11yClick (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599810432778/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1599810432778%22%2C%22timestamp%22%3A1599813984504%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:855931)
at g (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599810432778/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1599810432778%22%2C%22timestamp%22%3A1599813984504%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:1013436)
at a.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599810432778/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1599810432778%22%2C%22timestamp%22%3A1599813984504%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:35238)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599810432778/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1599810432778%22%2C%22timestamp%22%3A1599813984504%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:390780
at Wr.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599810432778/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1599810432778%22%2C%22timestamp%22%3A1599813984504%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:390154)
at Wr.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599810432778/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1599810432778%22%2C%22timestamp%22%3A1599813984504%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:390934)
at Cb.emitKeyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599810432778/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1599810432778%22%2C%22timestamp%22%3A1599813984504%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:1008642)
id: Bayes Chrome
Snapshot from 9/11/2020, 1:47:12 AM
```

**Comment by jbphet** [comment] 2020-09-11 20:07
I am unable to duplicate this, and tambo has passed CT for the last 4 interations, so I'm going to assume that this was an issue with some common code that has since been fixed, since I haven't been doing any work lately in tambo.

In case we need it, here is a version of the stack trace that isn't from a minimified file and is thus more readable.

```
tambo : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599846021512/tambo/tambo_en.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599846021512%22%2C%22timestamp%22%3A1599848074363%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: An event is required
Error: Assertion failed: An event is required
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599846021512/assert/js/assert.js:22:13)
at PressListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599846021512/scenery/js/listeners/PressListener.js:377:15)
at PressListener.click (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599846021512/scenery/js/listeners/PressListener.js:826:12)
at ArrowButton.a11yClick (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599846021512/sun/js/buttons/RectangularButtonView.js:614:25)
at increasedListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599846021512/sun/js/NumberSpinner.js:252:76)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599846021512/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599846021512/axon/js/Emitter.js:34:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599846021512/axon/js/Action.js:226:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599846021512/axon/js/Emitter.js:59:19)
at NumberSpinner.emitKeyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599846021512/sun/js/accessibility/AccessibleNumberSpinner.js:187:37)
id: Bayes Chrome
```

Closing.

**Comment by KatieWoe** [comment] 2020-09-14 15:09
This is back, reopening:
```
tambo : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600060945394%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'pointer' of undefined
TypeError: Cannot read property 'pointer' of undefined
at oA.canPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600060945394%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:635009)
at oA.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600060945394%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:635207)
at oA.click (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600060945394%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:637714)
at vb.a11yClick (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600060945394%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:855330)
at m (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600060945394%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:1012821)
at a.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600060945394%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:35238)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600060945394%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:390173
at Wr.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600060945394%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:389526)
at Wr.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600060945394%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:390327)
at Cb.emitKeyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600060945394%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:1007979)
id: Bayes Chrome
Snapshot from 9/13/2020, 10:38:01 PM

----------------------------------

tambo : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600067750305%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'pointer' of undefined
TypeError: Cannot read property 'pointer' of undefined
at oA.canPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600067750305%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:635009)
at oA.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600067750305%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:635207)
at oA.click (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600067750305%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:637714)
at vb.a11yClick (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600067750305%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:855330)
at m (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600067750305%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:1012821)
at a.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600067750305%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:35238)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600067750305%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:390173
at Wr.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600067750305%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:389526)
at Wr.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600067750305%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:390327)
at Cb.emitKeyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600067750305%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:1007979)
id: Bayes Chrome
Snapshot from 9/13/2020, 10:38:01 PM

----------------------------------

tambo : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600078072998%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'pointer' of undefined
TypeError: Cannot read property 'pointer' of undefined
at oA.canPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600078072998%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:635009)
at oA.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600078072998%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:635207)
at oA.click (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600078072998%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:637714)
at vb.a11yClick (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600078072998%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:855330)
at m (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600078072998%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:1012821)
at a.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600078072998%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:35238)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600078072998%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:390173
at Wr.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600078072998%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:389526)
at Wr.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600078072998%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:390327)
at Cb.emitKeyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600078072998%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:1007979)
id: Bayes Chrome
Snapshot from 9/13/2020, 10:38:01 PM

----------------------------------

tambo : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600089774162%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'pointer' of undefined
TypeError: Cannot read property 'pointer' of undefined
at oA.canPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600089774162%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:635009)
at oA.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600089774162%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:635207)
at oA.click (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600089774162%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:637714)
at vb.a11yClick (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600089774162%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:855330)
at m (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600089774162%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:1012821)
at a.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600089774162%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:35238)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600089774162%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:390173
at Wr.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600089774162%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:389526)
at Wr.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600089774162%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:390327)
at Cb.emitKeyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/build/phet/tambo_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600089774162%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:846:1007979)
id: Bayes Chrome
Snapshot from 9/13/2020, 10:38:01 PM

----------------------------------

tambo : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/tambo/tambo_en.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1600058281820%22%2C%22timestamp%22%3A1600065566355%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: An event is required
Error: Assertion failed: An event is required
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/assert/js/assert.js:22:13)
at PressListener.press (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/scenery/js/listeners/PressListener.js:377:15)
at PressListener.click (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/scenery/js/listeners/PressListener.js:826:12)
at ArrowButton.a11yClick (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/sun/js/buttons/RectangularButtonView.js:614:25)
at increasedListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/sun/js/NumberSpinner.js:252:76)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/axon/js/Emitter.js:34:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/axon/js/Action.js:226:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/axon/js/Emitter.js:59:19)
at NumberSpinner.emitKeyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1600058281820/sun/js/accessibility/AccessibleNumberSpinner.js:187:37)
id: Bayes Chrome
Snapshot from 9/13/2020, 10:38:01 PM
```

**Comment by jbphet** [comment] 2020-09-14 21:28
To duplicate this problem outside of fuzz testing:

1. load tambo (the non-built version works for this)
2. Go to the first screen
3. Use the tab key to navigate to the number spinner that controls the number of balls
4. Press the up arrow

I've done some investigation on this, and my research indicates that this is a general problem with the a11y code in `NumberSpinner` rather than a tambo-specific problem.  The issue occurs in the sun demo as well, and my guess is that the only reason this hasn't been caught before is that `NumberSpinner` has not yet been used in a published sim that has a11y enabled.

The reason that an `assert` is being thrown is that a listener in `NumberSpinner` is calling `RectangularButtonView.a11yClick`, but isn't providing an event, and further down in the stack - specifically in `PressListener.press` - an assert statement tests that an event was provided.

From the git history, it looks like @jessegreenberg and @zepumph were the ones who did most of the work for adding a11y to this component.  I'm going to assign it to @jessegreenberg to start with.  He may wish to create a common code issue for this if it turns out to be more then a minor code change.

**Comment by jbphet** [comment] 2020-09-14 21:29
I'm giving this a 'high priority' label since it is causing tambo to fail CT tests.

**Comment by jessegreenberg** [comment] 2020-09-15 22:34
Thanks @jbphet - this is caused by https://github.com/phetsims/scenery/issues/1076, taking over there.

**Comment by jessegreenberg** [comment] 2020-09-16 16:33
This is no longer on CT after changes in https://github.com/phetsims/scenery/issues/1076.

**Closed by jessegreenberg** 2020-09-16 16:33 UTC
Labels: priority:2-high, type:automated-testing
