### ISSUE TITLE
Launched sim freezes on splash screen with Mac + Safari

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/tambo#162] opened 2022-04-19 15:20 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3.1

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/799, when making changes in the studio tree and launching sim, the launched sim often freezes on the splash screen. When I tab back to the Studio wrapper, there is an error message. This also happens in master. 

This seems to be specific to Mac + Safari. I quickly tried a few other platforms (Mac + Chrome, Win10 + Chrome/Firefox) and didn't see this issue. 

**Steps to reproduce**
When the error message occurs varies. General steps:
1. In the studio wrapper, set any visibleProperty to false.
2. Preview sim 
3. Back in studio, set that property back to true.
4. Set a different visibleProperty to false 
5. Preview sim
6. Repeat as many times as needed to get the error. 

@KatieWoe was able to reproduce following the above steps. 

**Visuals**
<img width="494" alt="Screen Shot 2022-04-19 at 8 53 04 AM" src="https://user-images.githubusercontent.com/87318828/164011136-60e5763f-4993-44e9-b9fd-a059d9450129.png">

https://user-images.githubusercontent.com/87318828/164037608-36363c25-b887-46c7-9600-3684cd452e22.mp4

**Comment by samreid** [comment] 2022-04-19 17:11
@jonathanolson and @pixelzoom and I discussed this, and we agree it would be best for @jbphet to collaborate on the long-term fix.  We also noted that with fix proposed above, there is still a memory leak since `        window.addEventListener( 'touchstart', resumeAudioContext, false );` is not guarded.

@pixelzoom said this doesn't prevent progress on the Geometric Optics dev test, so we can wait for a good long-term solution.  But it does block the PhET-iO batch release, so I marked it as blocks-publication.

I'll commit the short-term fix and reassign to @jbphet for longer-term investigation.

**Comment by pixelzoom** [comment] 2022-04-19 17:14
@Nancy-Salpepi @KatieWoe note that we transferred this issue from geometric-optics-basics to tambo, since it is a general problem that needs to be addressed in soundManager.ts.   Please consider this non-blocking for GO and GO:B dev tests (https://github.com/phetsims/qa/issues/798, https://github.com/phetsims/qa/issues/799).

**Comment by KatieWoe** [comment] 2022-04-21 21:42
Belatedly linking to https://github.com/phetsims/qa/issues/798

**Comment by jbphet** [comment] 2022-04-22 20:29
I tried for about an hour to get the conditions that were causing this problem to occur on a MacBook pro running MacOS 12.3.1 and Safari 15.4, but was not able to reproduce it.  I suspect that there was something going on similar to what is described in #90 where the audio context is going through a different state other than 'suspended' or 'running'.  I've seen things like this before, but only on Apple devices.

I think just having a simple guard that doesn't re-add the listener if it's already there is reasonable, which is what @samreid implemented.  I just cleaned it up a bit.

@KatieWoe - Can you please have the QA team test this on master and make sure that the problem can't be reproduced anymore?

**Comment by jbphet** [comment] 2022-04-22 20:30
I've also assigned @Nancy-Salpepi, since I believe @KatieWoe mentioned something about having a lot going on next week.

**Comment by KatieWoe** [comment] 2022-04-22 22:29
I repeated steps that caused the bug in the dev test in master and the bug didn't occur, so I think we're good.

**Comment by samreid** [comment] 2022-04-22 22:33
@jbphet did you intend to leave the console.log statements?  Do you want to work with me since the problem was replicable on my Safari? And won't there be a memory leak on the window.addEventListener, since it has no guard?

```ts
        // Add a listener that will resume the audio context on the next touchstart.
        window.addEventListener( 'touchstart', resumeAudioContext, false );

        // Listen also for other user gesture events that can be used to resume the audio context.
        if ( !Display.userGestureEmitter.hasListener( resumeAudioContext ) ) {
          Display.userGestureEmitter.addListener( resumeAudioContext );
        }
```

**Comment by Nancy-Salpepi** [comment] 2022-04-30 17:26
Both Geometric Optics and CCK-DC look good on Master.

**Comment by jbphet** [comment] 2022-05-09 20:18
@samreid - Here are my answers to your questions above:

> @jbphet did you intend to leave the console.log statements?

I meant to leave in the one that says "AudioContext is now running".  I didn't mean to leave the other one, and have removed it.  Thanks for pointing that out.

> And won't there be a memory leak on the window.addEventListener, since it has no **guard?**

I don't think so.  I found multiple sources online that said, "If multiple identical EventListener s are registered on the same EventTarget with the same parameters, the duplicate instances are discarded."  Also, the listener is removed as soon as the `removeAudioContext` listener runs.

> Do you want to work with me since the problem was replicable on my Safari?

It doesn't seem worth the time in my opinion, since QA has verified that the problem no longer exists.

@samreid - If you're reasonably satisfied with these answers, I think the issue can be closed.

**Comment by samreid** [comment] 2022-05-11 20:33
Sounds good, thanks!  Closing.

**Closed by samreid** 2022-05-11 20:33 UTC
Labels: type:bug, dev:phet-io, status:blocks-publication
