### ISSUE TITLE
Can we use sound effects governed by the RemArc license?

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#34] opened 2018-08-28 16:39 UTC
@Ashton-Morris recently asked me whether we would be able to use sound effects from a set that was made available by the BBC, which can be seen at http://bbcsfx.acropolis.org.uk/.  The license is "RemArc" and is described here: https://github.com/bbcarchdev/Remarc/blob/master/doc/2016.09.27_RemArc_Content%20licence_Terms%20of%20Use_final.pdf.  

Is this license compatible with PhET, and could we use these sounds in our simulations?

**Comment by jbphet** [comment] 2018-08-28 19:16
Dialog between @Ahston-Morris and the contact listed on the BBC page:

> Hi Jake, 

> I have a licensing question. I am working as the sound designer with PhET at the University of Colorado. PhET creates free educational simulations to use in classrooms around the world. It’s under creative commons use and I was wondering if under this BBC license "for educational or research purposes” I would be able to use these in our simulations? 

> Thank you for your time!

> All the best,
> Ashton Morris

> ————

> Hi Ashton
> Yes – I think your proposed usage counts as ‘educational’
> Kind Regards
> Jake
> Executive Product Manager
> BBC Archive Development
> (additional address details removed)

**Comment by jbphet** [comment] 2018-08-28 19:17
@emily-phet - I'm assigning this to you because I don't know who might be able to answer this, and though you might.

**Comment by jbphet** [comment] 2018-08-28 19:28
> Which sounds are we talking about?

There's a link in the original comment at the top.

**Comment by emily-phet** [comment] 2018-08-28 19:34
Sorry - I meant what sounds from JT are we talking about?

**Comment by jbphet** [comment] 2018-08-28 19:36
Nothing specific for John Travoltage, it was just a general question about what could be used in future sound designs.

**Comment by samreid** [comment] 2023-03-25 05:09
Since @emily-phet confirmed RemArc is not consistent with our usage policies, it seems this question has been answered.  I searched for `RemArc` across our codebase and did not see any occurrences, so it doesn't seem used so far.  Also it seems it would be incompatible with PhET-iO.  Closing.

**Closed by samreid** 2023-03-25 05:09 UTC
